<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Product::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        $detail='<ul><li>Nike Dri-FIT ADV technology combines moisture-wicking fabric with advanced engineering and features to help you stay dry and comfortable</li><li>Raised knit in high-heat areas provides additional breathability where you need it most</li><li>Authentic design is the same worn by the pros on the field</li><li>Signature details let you show your Blues love wherever you go</li><li>Slim fit for a tailored feel</li><li>100% polyester</li><li>Machine wash</li<li>Imported</li></ul>';
        $description='<p>The Chelsea Home Vapor Match Shirt pairs authentic design details with lightweight, quick-drying fabric to help keep the world&rsquo;s biggest football stars cool and comfortable on the field. This product is made with 100% recycled polyester fibres.</p>';
        $data=[
            ['color_id'=>1,'rate'=>5,'title'=>'Áo đấu sân nhà Chelsea Cup 2021-22 Champions of Europe','slug'=>'ao-dau-san-nha-chelsea-cup-2021-22-champions-of-europe','code'=>'SP000001','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/1a.jpg,/photos/1/product/1b.jpg,/photos/1/product/1c.jpg','size'=>'S,M,L,XL,XXL','min'=>10,'max'=>999,'type'=>'men','condition'=>'hot','status'=>1,'cat_id'=>1,'child_cat_id'=>null,'brand_id'=>1,'quantity'=>2,'quantity_status'=>'less'],
            ['color_id'=>1,'rate'=>5,'title'=>'Áo đấu sân nhà Chelsea 2021-22','slug'=>'ao-dau-san-nha-chelsea-2021-22','code'=>'SP000002','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/2a.jpg,/photos/1/product/2b.jpg,/photos/1/product/2c.jpg','size'=>'S,M,L,XL,XXL','min'=>10,'max'=>999,'type'=>'men','condition'=>'hot','status'=>1,'cat_id'=>1,'child_cat_id'=>5,'brand_id'=>1,'quantity'=>10,'quantity_status'=>'stocking'],
            ['color_id'=>2,'rate'=>5,'title'=>'Áo thứ 3 Chelsea 2019-20','slug'=>'ao-thu-3-chelsea-2019-20','code'=>'SP000003','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/3a.jpg,/photos/1/product/3b.jpg,/photos/1/product/3c.jpg','size'=>'S,M,L,XL,XXL','min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>1,'child_cat_id'=>5,'brand_id'=>1,'quantity'=>10,'quantity_status'=>'stocking'],
            ['color_id'=>1,'rate'=>5,'title'=>'Áo thi đấu sân nhà Chelsea 20-21','slug'=>'ao-thi-dau-san-nha-chelsea-20-21','code'=>'SP000004','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/4a.jpg,/photos/1/product/4b.jpg,/photos/1/product/4c.jpg','size'=>'S,M,L,XL,XXL','min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>1,'child_cat_id'=>5,'brand_id'=>1,'quantity'=>10,'quantity_status'=>'stocking'],
            ['color_id'=>3,'rate'=>5,'title'=>'Áo thi đấu sân khách Chelsea 20-21 ','slug'=>'ao-thi-dau-san-khach-chelsea-20-21','code'=>'SP000005','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/5a.jpg,/photos/1/product/5b.jpg,/photos/1/product/5c.jpg','size'=>'S,M,L,XL,XXL','min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>1,'child_cat_id'=>5,'brand_id'=>1,'quantity'=>10,'quantity_status'=>'stocking'],
            ['color_id'=>3,'rate'=>5,'title'=>'Áo đấu cho thủ môn Chelsea 2021-22','slug'=>'ao-dau-cho-thu-mon-chelsea-2021-22','code'=>'SP000016','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/16a.jpg,/photos/1/product/16b.jpg,/photos/1/product/16c.jpg','size'=>'S,M,L,XL,XXL','min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>1,'child_cat_id'=>5,'brand_id'=>1,'quantity'=>10,'quantity_status'=>'stocking'],
            ['color_id'=>4,'rate'=>5,'title'=>'Áo thủ môn Chelsea 2020-21','slug'=>'ao-thu-mon-chelsea-2020-21','code'=>'SP000017','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/17a.jpg,/photos/1/product/17b.jpg,/photos/1/product/17c.jpg','size'=>'S,M,L,XL,XXL','min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>1,'child_cat_id'=>5,'brand_id'=>1,'quantity'=>10,'quantity_status'=>'stocking'],
            ['color_id'=>2,'rate'=>5,'title'=>'Chelsea Strike Drill Top - Đen','slug'=>'chelsea-strike-drill-top-den','code'=>'SP000006','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/6a.jpg','size'=>'S,M,L,XL,XXL','min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>2,'child_cat_id'=>null,'brand_id'=>1,'quantity'=>15,'quantity_status'=>'stocking'],
            ['color_id'=>2,'rate'=>5,'title'=>'Chelsea Strike Track Jacket - Đen','slug'=>'chelsea-strike-track-jacket-den','code'=>'SP000007','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/7a.jpg,/photos/1/product/7b.jpg,/photos/1/product/7c.jpg','size'=>'S,M,L,XL,XXL','min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>2,'child_cat_id'=>null,'brand_id'=>1,'quantity'=>15,'quantity_status'=>'stocking'],
            ['color_id'=>2,'rate'=>5,'title'=>'Áo khoác học viện Chelsea Dri-Fit - Màu xanh hoàng gia','slug'=>'ao-khoac-hoc-vien-chelsea-dri-fit-mau-xanh-hoang-gia','code'=>'SP000008','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/8a.jpg,/photos/1/product/8b.jpg,/photos/1/product/8c.jpg','size'=>'S,M,L,XL,XXL','min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>2,'child_cat_id'=>null,'brand_id'=>1,'quantity'=>15,'quantity_status'=>'stocking'],
            ['color_id'=>4,'rate'=>5,'title'=>'Áo len cổ lọ Chelsea - Xám','slug'=>'ao-len-co-lo-chelsea-xam','code'=>'SP000009','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/9a.jpg,/photos/1/product/9b.jpg,/photos/1/product/9c.jpg','size'=>'S,M,L,XL,XXL','min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>2,'child_cat_id'=>null,'brand_id'=>1,'quantity'=>15,'quantity_status'=>'stocking'],
            ['color_id'=>1,'rate'=>5,'title'=>'Áo sơ mi Chelsea Air Max Collection Special Edition- Nam','slug'=>'ao-so-mi-chelsea-air-max-collection-special-edition-nam','code'=>'SP000010','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/10a.jpg,/photos/1/product/10b.jpg,/photos/1/product/10c.jpg','size'=>'S,M,L,XL,XXL','min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>2,'child_cat_id'=>null,'brand_id'=>1,'quantity'=>15,'quantity_status'=>'stocking'],
            ['color_id'=>6,'rate'=>5,'title'=>'Chelsea Puffer Jacket- Trắng','slug'=>'chelsea-puffer-jacket-trang','code'=>'SP000011','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/11a.jpg,/photos/1/product/11b.jpg,/photos/1/product/11c.jpg','size'=>'S,M,L,XL,XXL','min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>2,'child_cat_id'=>null,'brand_id'=>1,'quantity'=>15,'quantity_status'=>'stocking'],
            ['color_id'=>1,'rate'=>5,'title'=>'Chelsea Strike Drill Top - Xanh da trời','slug'=>'chelsea-strike-drill-top-xanh-da-troi','code'=>'SP000012','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/12a.jpg,/photos/1/product/12b.jpg,/photos/1/product/12c.jpg','size'=>'S,M,L,XL,XXL','min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>2,'child_cat_id'=>null,'brand_id'=>1,'quantity'=>15,'quantity_status'=>'stocking'],
            ['color_id'=>2,'rate'=>5,'title'=>'Chelsea Dri Fit Training Top - Xanh lam đậm','slug'=>'chelsea-dri-fit-training-top-xanh-lam-dam','code'=>'SP000013','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/13a.jpg,/photos/1/product/13b.jpg,/photos/1/product/13c.jpg','size'=>'S,M,L,XL,XXL','min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>2,'child_cat_id'=>null,'brand_id'=>1,'quantity'=>20,'quantity_status'=>'stocking'],
            ['color_id'=>2,'rate'=>5,'title'=>'Chelsea Strike Top - Đen - Nữ','slug'=>'chelsea-strike-top-den-nu','code'=>'SP000014','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/14a.jpg,/photos/1/product/14b.jpg,/photos/1/product/14c.jpg','size'=>'S,M,L,XL,XXL','min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>2,'child_cat_id'=>null,'brand_id'=>1,'quantity'=>20,'quantity_status'=>'stocking'],
            ['color_id'=>6,'rate'=>5,'title'=>'Áo sơ mi Chelsea Air Max Collection Special Edition - Nữ','slug'=>'ao-so-mi-chelsea-air-max-collection-special-edition-nu','code'=>'SP000015','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/15a.jpg,/photos/1/product/15b.jpg,/photos/1/product/15c.jpg','size'=>'S,M,L,XL,XXL','min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>2,'child_cat_id'=>null,'brand_id'=>1,'quantity'=>20,'quantity_status'=>'stocking'],
            
            ['color_id'=>7,'rate'=>5,'title'=>'Áo chung kết Chelsea 1998 ECWC','slug'=>'ao-chung-ket-chelsea-1998-ecwc','code'=>'SP000018','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/18a.jpg,/photos/1/product/18b.jpg,/photos/1/product/18c.jpg','size'=>'S,M,L,XL,XXL','min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>3,'child_cat_id'=>null,'brand_id'=>1,'quantity'=>20,'quantity_status'=>'stocking'],
            ['color_id'=>1,'rate'=>4,'title'=>'Áo khoác thể thao Chelsea 1978','slug'=>'ao-khoac-the-thao-chelsea-1978','code'=>'SP000019','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/19a.jpg,/photos/1/product/19b.jpg,/photos/1/product/19c.jpg','size'=>'S,M,L,XL,XXL','min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>3,'child_cat_id'=>null,'brand_id'=>1,'quantity'=>20,'quantity_status'=>'stocking'],
            ['color_id'=>8,'rate'=>4,'title'=>'Áo đấu Chelsea 1990','slug'=>'ao-dau-chelsea-1990','code'=>'SP000020','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/20a.jpg,/photos/1/product/20b.jpg,/photos/1/product/20c.jpg','size'=>'S,M,L,XL,XXL','min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>3,'child_cat_id'=>null,'brand_id'=>1,'quantity'=>10,'quantity_status'=>'stocking'],
            ['color_id'=>1,'rate'=>4,'title'=>'Áo đấu Chelsea 1978','slug'=>'ao-dau-chelsea-1978','code'=>'SP000021','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/21a.jpg,/photos/1/product/21b.jpg,/photos/1/product/21c.jpg','size'=>'S,M,L,XL,XXL','min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>3,'child_cat_id'=>null,'brand_id'=>1,'quantity'=>10,'quantity_status'=>'stocking'],
            ['color_id'=>9,'rate'=>4,'title'=>'Áo đấu Chelsea 1998 sân khách','slug'=>'ao-dau-chelsea-1998-san-khach','code'=>'SP000022','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/22a.jpg,/photos/1/product/22b.jpg,/photos/1/product/22c.jpg','size'=>'S,M,L,XL,XXL','min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>3,'child_cat_id'=>null,'brand_id'=>1,'quantity'=>10,'quantity_status'=>'stocking'],
            ['color_id'=>1,'rate'=>4,'title'=>'Áo đấu Chelsea 1992','slug'=>'Áo đấu Chelsea 1992','code'=>'SP000023','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/23a.jpg,/photos/1/product/23b.jpg,/photos/1/product/23c.jpg','size'=>'S,M,L,XL,XXL','min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>3,'child_cat_id'=>null,'brand_id'=>1,'quantity'=>10,'quantity_status'=>'stocking'],
            ['color_id'=>1,'rate'=>4,'title'=>'Áo đấu sân khách năm 1988 Chelsea','slug'=>'ao-dau-san-khach-nam-1988-chelsea','code'=>'SP000024','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/24a.jpg,/photos/1/product/24b.jpg,/photos/1/product/24c.jpg','size'=>'S,M,L,XL,XXL','min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>3,'child_cat_id'=>null,'brand_id'=>1,'quantity'=>10,'quantity_status'=>'stocking'],
            ['color_id'=>1,'rate'=>4,'title'=>'Áo chung kết FA Cup 1997 Chelsea','slug'=>'ao-chung-ket-fa-cup-1997-chelsea','code'=>'SP000025','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/25a.jpg,/photos/1/product/25b.jpg,/photos/1/product/25c.jpg','size'=>'S,M,L,XL,XXL','min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>3,'child_cat_id'=>null,'brand_id'=>1,'quantity'=>10,'quantity_status'=>'stocking'],
            
            ['color_id'=>1,'rate'=>null,'title'=>'Áo thun huấn luyện Chelsea Strike - Trắng','slug'=>'ao-thun-huan-luyen-chelsea-strike-trang','code'=>'SP000026','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/26a.jpg,/photos/1/product/26b.jpg,/photos/1/product/26c.jpg','size'=>'null','min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>4,'child_cat_id'=>null,'brand_id'=>1,'quantity'=>10,'quantity_status'=>'stocking'],
            ['color_id'=>1,'rate'=>null,'title'=>'Áo thun Chelsea Crest - Xanh coban','slug'=>'ao-thun-chelsea-crest-xanh-coban','code'=>'SP000027','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/27a.jpg','size'=>'null','min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>4,'child_cat_id'=>null,'brand_id'=>1,'quantity'=>5,'quantity_status'=>'less'],
            
            ['color_id'=>null,'rate'=>null,'title'=>'Khẩu trang Chelsea 21-22','slug'=>'khau-trang-chelsea-21-22-kit-xanh-lam-vang-nguoi-lon','code'=>'SP000028','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/28a.jpg','size'=>null,'min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>4,'child_cat_id'=>null,'brand_id'=>1,'quantity'=>5,'quantity_status'=>'less'],
            ['color_id'=>null,'rate'=>null,'title'=>'Sân vận động Chelsea 3D','slug'=>'san-van-dong-chelsea-3d','code'=>'SP000029','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/29a.jpg,/photos/1/product/29b.jpg,/photos/1/product/29c.jpg','size'=>null,'min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>4,'child_cat_id'=>null,'brand_id'=>1,'quantity'=>1,'quantity_status'=>'less'],
            ['color_id'=>null,'rate'=>null,'title'=>'Cúp vô địch Chelsea UCL 2021 - 150mm','slug'=>'cup-vo-dich-chelsea-ucl-2021-150mm','code'=>'SP000030','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/30a.jpg','size'=>null,'min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>4,'child_cat_id'=>null,'brand_id'=>1,'quantity'=>12,'quantity_status'=>'stocking'],
            ['color_id'=>null,'rate'=>null,'title'=>'Chìa khóa cúp vô địch Chelsea UCL 2021','slug'=>'chia-khoa-cup-vo-dich-chelsea-ucl-2021','code'=>'SP000031','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/31a.jpg','size'=>null,'min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>4,'child_cat_id'=>null,'brand_id'=>1,'quantity'=>0,'quantity_status'=>'outOfStock'],
            ['color_id'=>null,'rate'=>null,'title'=>'Khăn quàng cổ vô địch Chelsea UCL 2021','slug'=>'khan-quang-co-vo-dich-chelsea-ucl-2021','code'=>'SP000032','detail'=>$detail,'description'=>$description,'photo'=>'/photos/1/product/32a.jpg','size'=>null,'min'=>10,'max'=>999,'type'=>'kids','condition'=>'hot','status'=>1,'cat_id'=>4,'child_cat_id'=>null,'brand_id'=>1,'quantity'=>0,'quantity_status'=>'outOfStock'],
        ];
        
        Product::insert($data);
    }
}
